### ISSUE TITLE
你好，请问下tailwindcss与naiveUI混用而不冲突的效果是如何实现的？非常感谢。

### ISSUE THREAD

**Issue by zzx58-027** [qingqingxuan/admin-work#13]
你好，请问下tailwindcss与naiveUI混用而不冲突的效果是如何实现的？非常感谢。

**Comment by qingqingxuan** [comment]
naive-ui官网已经给出了解决办法。参见：https://www.naiveui.com/zh-CN/os-theme/docs/style-position

**Comment by zzx58-027** [comment]
> 目前的解决办法就是把 tailwindcss 的版本降低一些

哦哦谢谢，另外请问我如果有些其他问题想请教有渠道吗？可以在这里提交issue吗？

**Comment by zzx58-027** [comment]
比如scss的应用范围，tailwindcss是出于什么地方的考虑使用的？组件样式里面还是用了很多的scss，tailwindcss只使用了很少一部分的感觉？

**Comment by qingqingxuan** [comment]
README.md 中有微信二维码，加好友邀请您进微信群，或者关注公众号 知码前端 也有联系方式。
tailwindcss和scss并不冲突。本项目中主要是使用tailwindcss封装好的一些样式，比较便捷

**Comment by zzx58-027** [comment]
可以教一下vue3+TS的项目里面vue-router怎么配置吗？主要是加上了TS之后，有点难看明白，router/index.ts 文件里的mapTwoLevelRouter有点懵...
好像和shims-vue.d.ts里面的配置冲突了？。。
感谢

<img width="1194" alt="2022-05-16_10-49-37" src="https://user-images.githubusercontent.com/77034104/168511719-216cd9d0-2941-4521-9a75-d62299681e14.png">
<img width="807" alt="2022-05-16_10-49-28" src="https://user-images.githubusercontent.com/77034104/168511727-13992a3a-334e-4422-91ad-be93a2925104.png">

**Comment by qingqingxuan** [comment]
components 写错了
