### ISSUE TITLE
系统管理-用户管理功能下，用户的头像不能正常显示。

### ISSUE THREAD

**Issue by dujun0909** [qingqingxuan/admin-work#2]
系统管理-用户管理 功能下用户的头像不能正常显示，图片路径为/vue-admin-work-p/static/images/img_avatar_01.jpeg，应该是项目名称路径不对导致的。
![image](https://user-images.githubusercontent.com/14818244/142347800-5e170ce2-23c4-4124-9934-f992d04ce13c.png)

**Comment by qingqingxuan** [comment]
感谢指正，bug已修复
