### ISSUE TITLE
请教一个问题，关于路由结构的

### ISSUE THREAD

**Issue by zguiyang** [qingqingxuan/admin-work#9]
看了下源码，发现代码中将多层嵌套路由通过``mapTwoLevelRouter``方法进行了类似扁平化的处理：
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/24975063/161933551-d2681cf7-385e-4739-895c-4b65578256ea.png">
1. 这样做的目的是什么呢？
2. 我发现这样处理后，访问页面时就会直接访问到``/next/menu2/menu-2-1/xxx``这样，不会继承到父组件了，假如我有一个子页面要继承父页面视图的时候，还能通过路由结构配置来达到继承的效果吗？

**Comment by qingqingxuan** [comment]
1、这样做的目的是为了实现多级缓存的功能，把多级缓存转成两级方便实现缓存
2、不是很明白你说的`子页面要继承父页面视图`是什么意思……
